SELECT GETDATE(), 
APP_NAME(), 
HOST_NAME(), 
DATEADD (DAY, 30, GETDATE()),
YEAR(GETDATE()),
MONTH ('04/11/2014'),
SUSER_SNAME();

SELECT @@FETCH_STATUS, @@CONNECTIONS, @@DATEFIRST, @@LANGUAGE, @@LOCK_TIMEOUT;

