CREATE SEQUENCE SEQ_Agencia
AS SMALLINT
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 10000
NO CYCLE;

SELECT NEXT VALUE FOR SEQ_Agencia

ALTER SEQUENCE SEQ_Agencia
RESTART WITH 4
INCREMENT BY 1
MINVALUE 1
MAXVALUE 10000
NO CYCLE;

ALTER SEQUENCE SEQ_Cargo
RESTART WITH 100
INCREMENT BY 100
MINVALUE 100
MAXVALUE 30000
CYCLE;

DROP SEQUENCE SEQ_Cargo

CREATE SEQUENCE SEQ_Cargo
AS INT
START WITH 100
INCREMENT BY 100
NO MINVALUE 
NO MAXVALUE 
CYCLE;

CREATE SEQUENCE SEQ_Personal
AS INT
START WITH 1
INCREMENT BY 1
MINVALUE 0
NO MAXVALUE 
CYCLE;

DROP SEQUENCE SEQ_Personal

INSERT INTO DBO.Agencia (NroAgencia,
						 DesAgencia,
						 DirAgencia,
						 TelAgencia)
VALUES (NEXT VALUE FOR SEQ_Agencia,
        'ASUNCION',
		'PALMA Y CHILE',
		'021-495959'),
	    (NEXT VALUE FOR SEQ_Agencia,
        'CDE',
		'ADRIAN JARA Y BRASIL',
		'061-440440'),
	    (NEXT VALUE FOR SEQ_Agencia,
        'ENCARNACION',
		'CARLOS A. LOPEZ Y MCAL.ESTIGARRIBIA',
		'071-550550');

SET IDENTITY_INSERT AGENCIA ON
SELECT NEXT VALUE FOR SEQ_Agencia