ALTER TABLE AGENCIA DISABLE TRIGGER ALL

INSERT INTO AGENCIA (CODAGENCIA, DESCRIPCIONAGENCIA, DIRECCION, TELEFONO)
OUTPUT INSERTED.*
VALUES (100, 'CASA CENTRAL', 'ASUNCIÓN', '021-496322'),
	   (101, 'CDE', 'CIUDAD DEL ESTE', '061-608033'),
	   (102, 'ENCARNACIÓN', 'ENCARNACIÓN', '071-608033');

INSERT INTO AGENCIA (CODAGENCIA, DESCRIPCIONAGENCIA, DIRECCION, TELEFONO)
--OUTPUT INSERTED.*
VALUES (103, 'CASA CENTRAL', 'ASUNCIÓN', '021-496322'),
	   (104, 'CDE', 'CIUDAD DEL ESTE', '061-608033'),
	   (105, 'ENCARNACIÓN', 'ENCARNACIÓN', '071-608033');

SELECT * FROM AGENCIA;

DELETE FROM AGENCIA
OUTPUT DELETED.*
WHERE CODAGENCIA BETWEEN 100 AND 105;


DECLARE @VAGENCIA TABLE 
([CodAgencia] [smallint] NOT NULL,
 [DescripcionAgencia] [char](30) NOT NULL,
 [Direccion] [char](60) NOT NULL,
 [Telefono] [char](15) NULL
);

INSERT INTO AGENCIA (CODAGENCIA, DESCRIPCIONAGENCIA, DIRECCION, TELEFONO)
OUTPUT INSERTED.* INTO @VAGENCIA
VALUES (100, 'CASA CENTRAL', 'ASUNCIÓN', '021-496322'),
	   (101, 'CDE', 'CIUDAD DEL ESTE', '061-608033'),
	   (102, 'ENCARNACIÓN', 'ENCARNACIÓN', '071-608033'),
       (103, 'CASA CENTRAL', 'ASUNCIÓN', '021-496322'),
	   (104, 'CDE', 'CIUDAD DEL ESTE', '061-608033'),
	   (105, 'ENCARNACIÓN', 'ENCARNACIÓN', '071-608033');

SELECT * FROM @VAGENCIA;


DECLARE @VAGENCIA TABLE 
([CodAgencia] [smallint] NOT NULL,
 [DescripcionAgencia] [char](30) NOT NULL,
 [Direccion] [char](60) NOT NULL,
 [Telefono] [char](15) NULL
);

DELETE FROM AGENCIA
OUTPUT DELETED.* INTO @VAGENCIA
WHERE CODAGENCIA BETWEEN 100 AND 105;

SELECT * FROM AGENCIA;
SELECT * FROM @VAGENCIA;

UPDATE AGENCIA SET TELEFONO = '0' + TELEFONO,
DIRECCION = '|' + DIRECCION
OUTPUT DELETED.CODAGENCIA, DELETED.DIRECCION, DELETED.TELEFONO,
       INSERTED.CODAGENCIA, INSERTED.DIRECCION, INSERTED.TELEFONO
WHERE CODAGENCIA BETWEEN 100 AND 105;
